"""The module contains implementation of constant variables"""

LEVEL_SECTION_PREFIX = 'level_section_'

## Default Progress Bar Values ##
PB_DEFAULT_FUELLED_SLOT = '█'
PB_DEFAULT_MISSING_SLOT = '_'
PB_DEFAULT_BARRIER = '|'



## ANSI Escape Codes for Colors and Styles ##

# Reset formatting
ANSI_RESET_ALL = '\033[0m'

# Text Styles
TXT_STYLE_BOLD = '\033[1m'
TXT_STYLE_FAINT = '\033[2m'
TXT_STYLE_ITALIC = '\033[3m'
TXT_STYLE_UNDERLINE = '\033[4m'
TXT_STYLE_BLINK = '\033[5m'
TXT_STYLE_INVERSE = '\033[7m' # Swap foreground and background
TXT_STYLE_HIDDEN = '\033[8m '
TXT_STYLE_STRIKETHROUGH = '\033[9m'

TXT_STYLES = [
          TXT_STYLE_BOLD,
          TXT_STYLE_FAINT,
          TXT_STYLE_ITALIC,
          TXT_STYLE_UNDERLINE,
          TXT_STYLE_BLINK,
          TXT_STYLE_INVERSE,
          TXT_STYLE_HIDDEN,
          TXT_STYLE_STRIKETHROUGH
          ]

# Foreground Colors (Normal)
TXT_COLOR_DEFAULT = '\033[39m'
TXT_COLOR_BLACK = '\033[30m'
TXT_COLOR_RED = '\033[31m'
TXT_COLOR_GREEN = '\033[32m'
TXT_COLOR_YELLOW = '\033[33m'
TXT_COLOR_BLUE = '\033[34m'
TXT_COLOR_MAGENTA = '\033[35m'
TXT_COLOR_CYAN = '\033[36m'
TXT_COLOR_WHITE = '\033[37m'

TXT_COLORS = [
          TXT_COLOR_DEFAULT,
          TXT_COLOR_BLACK,
          TXT_COLOR_RED,
          TXT_COLOR_GREEN,
          TXT_COLOR_YELLOW,
          TXT_COLOR_BLUE,
          TXT_COLOR_MAGENTA,
          TXT_COLOR_CYAN,
          TXT_COLOR_WHITE
          ]

# Foreground Colors (Bright/High Intensity)
TXT_COLOR_BRIGHT_BLACK = '\033[90m'
TXT_COLOR_BRIGHT_RED = '\033[91m'
TXT_COLOR_BRIGHT_GREEN = '\033[92m'
TXT_COLOR_BRIGHT_YELLOW = '\033[93m'
TXT_COLOR_BRIGHT_BLUE = '\033[94m'
TXT_COLOR_BRIGHT_MAGENTA = '\033[95m'
TXT_COLOR_BRIGHT_CYAN = '\033[96m'
TXT_COLOR_BRIGHT_WHITE = '\033[97m'

TXT_COLORS_BRIGHT = [
          TXT_COLOR_BRIGHT_BLACK,
          TXT_COLOR_BRIGHT_RED,
          TXT_COLOR_BRIGHT_GREEN,
          TXT_COLOR_BRIGHT_YELLOW,
          TXT_COLOR_BRIGHT_BLUE,
          TXT_COLOR_BRIGHT_MAGENTA,
          TXT_COLOR_BRIGHT_CYAN,
          TXT_COLOR_BRIGHT_WHITE
          ]

# Background Colors (Normal)
BG_COLOR_DEFAULT = '\033[49m'
BG_COLOR_BLACK = '\033[40m'
BG_COLOR_RED = '\033[41m'
BG_COLOR_GREEN = '\033[42m'
BG_COLOR_YELLOW = '\033[43m'
BG_COLOR_BLUE = '\033[44m'
BG_COLOR_MAGENTA = '\033[45m'
BG_COLOR_CYAN = '\033[46m'
BG_COLOR_WHITE = '\033[47m'

BG_COLORS = [
          BG_COLOR_DEFAULT,
          BG_COLOR_BLACK,
          BG_COLOR_RED,
          BG_COLOR_GREEN,
          BG_COLOR_YELLOW,
          BG_COLOR_BLUE,
          BG_COLOR_MAGENTA,
          BG_COLOR_CYAN,
          BG_COLOR_WHITE
          ]

# Background Colors (Bright/High Intensity)
BG_COLOR_BRIGHT_BLACK = '\033[100m'
BG_COLOR_BRIGHT_RED = '\033[101m'
BG_COLOR_BRIGHT_GREEN = '\033[102m'
BG_COLOR_BRIGHT_YELLOW = '\033[103m'
BG_COLOR_BRIGHT_BLUE = '\033[104m'
BG_COLOR_BRIGHT_MAGENTA = '\033[105m'
BG_COLOR_BRIGHT_CYAN = '\033[106m'
BG_COLOR_BRIGHT_WHITE = '\033[107m'

BG_COLORS_BRIGHT = [
          BG_COLOR_BRIGHT_BLACK,
          BG_COLOR_BRIGHT_RED,
          BG_COLOR_BRIGHT_GREEN,
          BG_COLOR_BRIGHT_YELLOW,
          BG_COLOR_BRIGHT_BLUE,
          BG_COLOR_BRIGHT_MAGENTA,
          BG_COLOR_BRIGHT_CYAN,
          BG_COLOR_BRIGHT_WHITE
          ]
